// eslint-disable-next-line @typescript-eslint/no-var-requires
require('dotenv').config();

module.exports = {
  development: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: process.env.DB_DIALECT,
    dialectOptions: { useUTC: false },
    timezone: '-05:00',
    define: { schema: process.env.DB_SCHEMA, underscored: true },
    migrationStorageTableName: 'sequelize_migrations',
    seederStorage: 'sequelize',
    seederStorageTableName: 'sequelize_data',
    // encrypt: process.env.DB_ENCRYPT,
    // pool: {
    //   max: parseInt(process.env.DB_POOL_MAX),
    //   min: parseInt(process.env.DB_POOL_MIN),
    //   acquire: parseInt(process.env.DB_POOL_ACQUIRE),
    //   idle: parseInt(process.env.DB_POOL_IDLE),
    // },
  },
  test: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: process.env.DB_DIALECT,
    dialectOptions: { useUTC: false },
    timezone: '-05:00',
    define: { schema: process.env.DB_SCHEMA, underscored: true },
    migrationStorageTableName: 'sequelize_migrations',
    seederStorage: 'sequelize',
    seederStorageTableName: 'sequelize_data',
    // encrypt: process.env.DB_ENCRYPT,
    // pool: {
    //   max: parseInt(process.env.DB_POOL_MAX),
    //   min: parseInt(process.env.DB_POOL_MIN),
    //   acquire: parseInt(process.env.DB_POOL_ACQUIRE),
    //   idle: parseInt(process.env.DB_POOL_IDLE),
    // },
  },
  production: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: process.env.DB_DIALECT,
    dialectOptions: { useUTC: false },
    timezone: '-05:00',
    define: { schema: process.env.DB_SCHEMA, underscored: true },
    migrationStorageTableName: 'sequelize_migrations',
    seederStorage: 'sequelize',
    seederStorageTableName: 'sequelize_data',
    // encrypt: process.env.DB_ENCRYPT,
    // pool: {
    //   max: parseInt(process.env.DB_POOL_MAX),
    //   min: parseInt(process.env.DB_POOL_MIN),
    //   acquire: parseInt(process.env.DB_POOL_ACQUIRE),
    //   idle: parseInt(process.env.DB_POOL_IDLE),
    // },
  },
};
